---
openapi: 3.0.0
info:
  title: Violation Report API
  version: 1.0.0
paths:
  /api/v1/generate-violation-report:
    post:
      summary: Generate and send computer room violation reports within seven days
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  example: user@example.com
      responses:
        '200':
          description: Report generation request accepted
          content:
            application/json:
              schema:
                type: object
                properties:
                  reportId:
                    type: string
                    example: 12345
        '400':
          description: Request parameter error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: Invalid email address

  /api/v1/report-status/{reportId}:
    get:
      summary: Query report generation status
      parameters:
        - name: reportId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Report generation status
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: pending

  /api/v1/violation-statistics:
    get:
      summary: Query the violation record statistics within a specified time period
      parameters:
        - name: startTime
          in: query
          required: true
          schema:
            type: string
            format: date-time
        - name: endTime
          in: query
          required: true
          schema:
            type: string
            format: date-time
      responses:
        '200':
          description: Violation record statistics
          content:
            application/json:
              schema:
                type: object
                properties:
                  violations:
                    type: array
                    items:
                      type: object
                      properties:
                        timestamp:
                          type: string
                          format: date-time
                        cameraId:
                          type: string
                        violationType:
                          type: string
        '400':
          description: Request parameter error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: Invalid time format
servers:
  # Added by API Auto Mocking Plugin
  - description: SwaggerHub API Auto Mocking
    url: https://virtserver.swaggerhub.com/ai2024/ai2024_dashboard_api/1.0.0